name: icesat2-cookbook
channels:
- conda-forge
- nodefaults
dependencies:
- matplotlib *
- pre-commit *
- jupyterlab *
- jupyterlab-myst *
- earthaccess *
- geodatasets *
- geopandas *
- icepyx *
- ipympl *
- ipykernel *
- mystmd *
- numpy *
- pyproj *
- rioxarray *
- sliderule *
- xarray *
- h5py *
- shapely *
- contextily * 
- fiona *
- scipy
- earthengine-api
- geemap
- pillow 
