name: trigger-book-build
on:
  workflow_run:
    workflows: ["trigger-pixi-environment"]
    types: [completed]

jobs:
  build:
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    secrets:
      EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USER }}
      EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASS }}
    with:
      artifact_name: book-zip-${{ github.event.number }}
      build_from_code_artifact: 'true'
      code_artifact_name: code-zip-${{ github.event.number }}
      workflow: 'trigger-pixi-environment.yaml'
      base_url: '/${{ github.event.repository.name }}/_preview/${{ github.event.number }}'
      # Other input options are possible, see ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml
